language: julia
julia:
    - 0.6
    - 0.7
    - 1.0
    - nightly
after_success:
  # push coverage results
  - julia -e 'VERSION >= v"0.7.0-DEV.5183" && using Pkg; cd(Pkg.dir("BarycentricLagrange")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'VERSION >= v"0.7.0-DEV.5183" && using Pkg; cd(Pkg.dir("BarycentricLagrange")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
