name = "BarycentricLagrange"
uuid = "12dacfb5-bf08-5650-91b3-4b505835478a"
author = "Ludvig af Klinteberg <ludvigak@kth.se>"
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
julia = ">= 0.6"

[extras]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[targets]
test = ["Compat"]
